$ aleph C standard ice files
'include' "iceC/base"
'include' "iceC/getint"
'include' "iceC/getline"
'include' "iceC/putasstring"
'include' "iceC/putint"
'include' "iceC/putline"
'include' "iceC/putstring"
'include' "iceC/waitfor"
'include' "iceC/stdin"
'include' "iceC/stdarg"
'include' "iceC/stdout"
'include' "iceC/formatprint"
'include' "iceC/hash"
