$ aleph C standard ice files
'include' "ice/aleph-stdbase"
'include' "ice/aleph-stdgetint"
'include' "ice/aleph-stdgetline"
'include' "ice/aleph-stdputasstring"
'include' "ice/aleph-stdputint"
'include' "ice/aleph-stdputline"
'include' "ice/aleph-stdputstring"
'include' "ice/aleph-stdwait"
'include' "ice/aleph-stdin"
'include' "ice/aleph-stdarg"
'include' "ice/aleph-stdout"
'include' "ice/aleph-stdformatprint"
'include' "ice/aleph-stdhash"
