$ aleph C standard ice files
'include' "ice/base"
'include' "ice/getint"
'include' "ice/getline"
'include' "ice/putasstring"
'include' "ice/putint"
'include' "ice/putline"
'include' "ice/putstring"
'include' "ice/waitfor"
'include' "ice/stdin"
'include' "ice/stdarg"
'include' "ice/stdout"
'include' "ice/formatprint"
'include' "ice/hash"
