$ aleph standard files
'include' "icejs/base"
'include' "icejs/getint"
'include' "icejs/getline"
'include' "icejs/putasstring"
'include' "icejs/putint"
'include' "icejs/putline"
'include' "icejs/putstring"
'include' "icejs/waitfor"
'include' "icejs/stdin"
'include' "icejs/stdarg"
'include' "icejs/stdout"
'include' "icejs/formatprint"
'include' "icejs/hash"
